
name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Use the Node.js version you prefer

      - name: Install dependencies
        run: npm install

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Vercel token
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # Vercel organization ID
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Vercel project ID
